version: '3.1'
services:
  db:
    image: mariadb:10.4.6 #mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111 #root
    ports:
      - 3306:3306
#    adminer:
#      image: adminer:4.7.7
#      restart: always
#      ports:
#        - 8080:8080