spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/rsupport?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

custom:
  addressbook:
    file.path: "src/main/resources/data/member.csv"
