spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsupport
    username: root
    password: 111111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
